### PR TITLE
fixes #67 add checkout session events

### LINKED ISSUE #67: checkout.session webhook event not being handled
hey there,

first of all you're a legend for making this lib.
now on to business...

i'm trying to use `stripe::Event` to parse my webhook notifications, works for all subscriptions but `checkout.session.completed` doesn't seem to be being handled. i'll have a look around and see if i can find the cause.

```
Json deserialize error: unknown variant `checkout.session`, expected one of `account`, `application_fee`, ...
```

### PR DESCRIPTION
**Pull request by margh**
fixes https://github.com/wyyerd/stripe-rs/issues/67

### CODE REVIEW

File: tests/encoding.rs [hunk 1]
```diff
@@ -288,3 +288,54 @@ fn deserialize_customer_with_source() {
     let result = serde_json::from_value::<Customer>(example);
     assert!(result.is_ok(), "expected ok; was {:?}", result);
 }
+
+#[test]
```
Comment (kestred) [inline tests/encoding.rs]: ❤️

**Comment by kestred** [comment]
Sometimes serde provides poor error propogation for inner types of enum variants; most of the time that's only with `untagged` variants, but I'll look in to why `checkout.session.completed` doesn't parse when I've got a bit time.
